import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto, Poppins } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <h1>Main Layout</h1> */}
        <div className="container">
          {/* <Navbar/> */}
          {children}
          {/* <Footer/> */}
        </div>
      </body>
    </html>
  )
}
